spring:
  datasource:   # springboot가 어떤 데이터한 데이터베이스를 가리키도록 할 것인지
    url: "jdbc:mysql://localhost/library" # jdbc:mysql:// = "jdbc를 이용해 mysql에 접근"
    username: "root"                      # localhost : 접근하려는 mysql은 localhost에 있음
    pasword:                              # library : 접근하려는 DB는 library이다
    driver-class-name: com.mysql.cj.jdbc.Driver

